name: "Someone's name"
title: "Fakebook Exposed"
description: ""

url: https://data4democracy.github.io
baseurl: "/equifake"
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed

include: ["_pages"]

collections:
  - props