name: "FacebookExposed"
title: "FacebookExposed"
description: "FacebookExposed shows you how you were targeted by fake pages and Russian propaganda in 2016."

url: http://fbexposed.com
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed

include: ["_pages"]

collections:
  - props