name: "Someone's name"
title: "Equifake"
description: "Words"

url: https://data4democracy.github.io/equifake
baseurl: ""
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed

include: ["_pages"]